[package]
name = "sqd-array"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
arrow = { workspace = true }
arrow-buffer = { workspace = true }
tempfile = { workspace = true }

[dev-dependencies]
parquet = { workspace = true }
