[package]
name = "sqd-node"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
axum = "0.7.5"
bytes = "1.6.1"
clap = { version = "4.5.9", features = ["derive"] }
ouroboros = "0.18.4"
flate2 = "1.0.30"
futures = "0.3.30"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqd-data = { path = "../data" }
sqd-dataset = { path = "../dataset" }
sqd-polars = { path = "../polars" }
sqd-primitives = { path = "../primitives", features = ["serde"] }
sqd-query = { path = "../query", features = ["storage"] }
sqd-storage = { path = "../storage" }
tokio = { version = "1.38.0", features = ["full"] }
tokio-util = { version = "0.7.11", features = ["io"] }

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "main"
harness = false